---
- name: Mise à niveau des CISCO IOS
  hosts: labcisco-switchs
  gather_facts: no
  vars:
    upgrade_ios_version: 17.11.01
    upgrade_filename: cat9k_iosxe.17.11.01.SPA.bin

  tasks:
    - name: "Receuillir les informations de l'appareil"
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: facts_output

    - name: "Imprimer les informations"
      debug:
        msg: "La version actuel est {{ facts_output['ansible_facts']['ansible_net_version'] }}"

    - debug:
        msg:
          - "La version installé est inférieur, alors on procède avec la mise à niveau"
      when: upgrade_ios_version != facts_output['ansible_facts']['ansible_net_version']

    - name: "Installer et activer la nouvelle image IOS XE"
      cisco.ios.ios_command:
        commands:
          - command: 'install add file flash:{{ upgrade_filename }} activate commit'
            prompt: 'This operation may require a reload of the system.'
            answer: 'y'
      register: install_activate_output
      vars:
        ansible_command_timeout: 1200
      when: upgrade_ios_version != facts_output['ansible_facts']['ansible_net_version']

    - debug:
        var: install_activate_output
      when: upgrade_ios_version != facts_output['ansible_facts']['ansible_net_version']

    - name: "Attendre le redémarrage de l'appareil"
      wait_for_connection:
        delay: 360
        sleep: 60
        timeout: 1800
      when: upgrade_ios_version != facts_output['ansible_facts']['ansible_net_version']

    - name: "Reprendre les informations de l'appareil"
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: facts_output_new

    - name: New Version
      debug:
        msg: "New Version is {{ facts_output_new['ansible_facts']['ansible_net_version'] }}, Upgrade Successfully Completed"
      when: facts_output['ansible_facts']['ansible_net_version'] != facts_output_new['ansible_facts']['ansible_net_version']
