---
- name: Ping les appareils dans cisco
  hosts: labcisco

  tasks:
      - name: Gather facts (ios)
        cisco.ios.ios_facts:
        when: ansible_network_os == 'cisco.ios.ios'

      - name: Display some facts
        debug:
            msg: "Host {{ ansible_net_hostname }} ,OS {{ ansible_net_version }}, Image {{ ansible_net_image }}, Model {{ ansible_net_model }}"
