---
- name: Ping les appareils dans cisco
  hosts: cisco

  tasks:
      - name: Gather facts (ios)
        cisco.ios.ios_facts:
        when: ansible_network_os == 'cisco.ios.ios'

      - name: Display some facts
        debug:
            msg: "Host {{ ansible_net_hostname }} ,OS {{ ansible_net_version }}"

      - name: Backup device (ios)
        cisco.ios.ios_config:
            backup: true
            backup_options:
               dir_path: "./backups/{{ inventory_hostname }}"
        when: ansible_network_os == 'cisco.ios.ios'
